// <auto-generated />
namespace TIQRI.ITS.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class dev : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dev));
        
        string IMigrationMetadata.Id
        {
            get { return "202203102042396_dev"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
