// <auto-generated />
namespace TIQRI.ITS.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _20211116_init10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20211116_init10));
        
        string IMigrationMetadata.Id
        {
            get { return "202111161927568_20211116_init10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
